apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: stateless-component
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
    - name: server
      image: nginx:latest
      resources: 
        cpu: 
         required: 100m
        memory: 
         required: 128Mi
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
